// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Helper function to ensure pgbouncer=true is set for connection poolers
// This prevents "prepared statement already exists" errors during migrations
function ensurePgbouncerParam(connectionString: string): string {
  const isPooler = connectionString.includes(':6543') || 
                   connectionString.includes('pooler.supabase.com') || 
                   connectionString.includes('pooler');
  
  if (!isPooler) {
    return connectionString;
  }
  
  // Check if pgbouncer is already set
  if (connectionString.includes('pgbouncer=')) {
    return connectionString;
  }
  
  // Parse and add pgbouncer parameter
  try {
    const url = new URL(connectionString);
    url.searchParams.set('pgbouncer', 'true');
    return url.toString();
  } catch (error) {
    // If URL parsing fails, try string manipulation
    const separator = connectionString.includes('?') ? '&' : '?';
    return `${connectionString}${separator}pgbouncer=true`;
  }
}

// For migrations:
// - In Vercel/serverless: Always use DATABASE_URL (pooler connection, port 6543)
// - In local dev: Prefer DIRECT_URL if available, otherwise use DATABASE_URL
// 
// IMPORTANT: For Supabase on Vercel, DATABASE_URL must use the Transaction Pooler (port 6543)
// The direct connection (port 5432) is not reachable from Vercel's build environment
const isVercel = process.env.VERCEL === "1" || !!process.env.VERCEL_ENV;
let migrationUrl: string | undefined;
let directUrl: string | undefined;

if (isVercel) {
  // In Vercel, always use DATABASE_URL (should be pooler connection)
  migrationUrl = process.env["DATABASE_URL"];
  if (!migrationUrl) {
    throw new Error("DATABASE_URL must be set in Vercel environment variables");
  }
  migrationUrl = ensurePgbouncerParam(migrationUrl);
  
  // Use DIRECT_URL if available, otherwise use DATABASE_URL for directUrl
  directUrl = process.env["DIRECT_URL"] || migrationUrl;
} else {
  // In local dev, prefer DIRECT_URL for faster migrations, fallback to DATABASE_URL
  migrationUrl = process.env["DIRECT_URL"] || process.env["DATABASE_URL"];
  if (!migrationUrl) {
    throw new Error("Either DIRECT_URL or DATABASE_URL must be set for Prisma migrations");
  }
  migrationUrl = ensurePgbouncerParam(migrationUrl);
  
  // For local dev, use DIRECT_URL if available, otherwise DATABASE_URL
  directUrl = process.env["DIRECT_URL"] || process.env["DATABASE_URL"];
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: migrationUrl,
    directUrl: directUrl,
  },
});
